### ISSUE TITLE
Error on start vagrant-run-up-test.sh

### ISSUE THREAD

**Issue by theShadow89** [jayunit100/SparkStreamingCassandraDemo#1]
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "run", "--name", "scale2", "-d", "-v", "/home/stefano/SparkStreamingApps/deploy:/scale-shared", "-v", "/home/stefano/SparkStreamingApps/deploy:/vagrant", "-h", "scale2.docker", "--privileged=true", "--link", "scale1:scale1.docker", "--link", "cassandra1:cassandra1.docker", "839deaeff2fb", {:notify=>[:stdout, :stderr]}]

Stderr: time="2015-02-08T18:29:01+01:00" level="fatal" msg="Error response from daemon: Cannot start container be5adb9fdc63d53c0bffdc33414bcf71b10d540dca317d78f0335a90a7bb9dbe: Cannot link to a non running container: /scale1 AS /scale2/scale1.docker" 

Stdout: be5adb9fdc63d53c0bffdc33414bcf71b10d540dca317d78f0335a90a7bb9dbe

RUNNING smoke tests...
FATA[0000] Error response from daemon: Container scale1 is not running

**Comment by jayunit100** [comment]
Thanks! This code is sorta in an intermediate state, made some modifications to containers for another env.

If you go back a few commits I'm sure it will work... But let me update this and test it for you and I'll ping you back.

**Comment by jayunit100** [comment]
fixed @theShadow89  !!!!!!!!!!! please test again :)

**Comment by jayunit100** [comment]
@theShadow89 .  Let me know if its now working for you. thanks !

**Comment by theShadow89** [comment]
Now work ! thanks!
